### PR TITLE
Fixed kotlin-1.2.71 compatibility

### PR DESCRIPTION
**Pull request by callmetango**
* bumped Kotlin to version 1.2.71
* fixed build output paths of both modules 'content_script' and 'popup'
* made gradlew shell script executable
* added package.json and package-lock.json
* added npm modules npx and web-ext
* updated build instructions in README.md to use package.json and `npx`
* added /node_modules to .gitignore

### CODE REVIEW

**Comment by cypressious** [comment]
Hey @callmetango, thx for the PR!

Do you think it's necessary to pull in the NPM dependencies? I think it's a bit inelegant to have both, a build.gradle and a package.json.

Otherwise, looks good.

**Comment by callmetango** [comment]
@cypressious Yes, I do not admire the two build systems too so I dropped the node package stuff as you requested.

Ps. Sorry for the delay. Github was permanently killing my login session for some reason.

**Comment by cypressious** [comment]
@callmetango great! Then we should probalby also get rid of the changes to the README and I can merge.

**Comment by cypressious** [comment]
Dependencies were update din #2, so I'm closing this. Thanks for the involvement.

**Pull request closed without merging**
